### ISSUE TITLE
Support for seach by URL

### ISSUE THREAD

**Issue by UndarkAido** [InBrowserApp/tldr.inbrowser.app#10]
I'd like to add TLDR to my browser as a search engine which would require an endpoint to navigate to. I could do something like `https://tldr.inbrowser.app/pages/common/%s`, but that wouldn't work for everything.

**Comment by rwv** [comment]
https://tldr.inbrowser.app/search/activate-site-search

**Comment by UndarkAido** [comment]
Oh cool, thank you! It'd be nice if that was publicized in some way, maybe

**Comment by UndarkAido** [comment]
Is there a suggest URL?

**Comment by rwv** [comment]
https://github.com/InBrowserApp/tldr.inbrowser.app/blob/main/public/opensearch.xml

https://tldr.inbrowser.app/search?query={searchTerms}
