### ISSUE TITLE
opensearch.xml Not Found in Firefox

### ISSUE THREAD

**Issue by smrqdt** [InBrowserApp/tldr.inbrowser.app#12]
tldr.inbrowser.app announces an opensearch plugin via link header, but the referenced [opensearch.xml](https://tldr.inbrowser.app/opensearch.xml) returns a 404.

As the file [exists](https://github.com/InBrowserApp/tldr.inbrowser.app/blob/main/public/opensearch.xml) in this repo, I guess it's some deployment issue.

**Comment by smrqdt** [comment]
5 seconds _after_ creating the issue, I checked with curl, and it exists, should have done that first. o.0

So this seems to be some Firefox related issue: I use Firefox 110.0.1 (64-bit) on Arch Linux. I checked in a clean browser profile without any addons as well as in Firefox Dev Editin 111.0b8 (64-bit), same issue.

**Comment by rwv** [comment]
This issue is related to service worker. The service worker didn’t register the opensearch xml.

**Comment by rwv** [comment]
This deployment should be ready in around 5 minute. However, to update service worker,  you need refresh and close Firefox fully or activate latest service worker in developer tools.
