### ISSUE TITLE
Disable changing suggestions inside search box

### ISSUE THREAD

**Issue by tpiekarski** [InBrowserApp/tldr.inbrowser.app#13]
The search box is constantly displaying changing suggestions on what to search for. 
I think this is a distraction and I wanted to suggest either removing it or at least offering a setting to disable it.

I am not sure how you feel about it, but I have often trouble focusing when there is anything constantly moving in my peripheral vision.

I know I can just type something into that box as a workaround, but well anyway I wanted to open such an issue and should you agree I could try to open a PR to make this suggestions an option to be displayed.

**Comment by tpiekarski** [comment]
Bump :-)

**Comment by rwv** [comment]
fixed
