### ISSUE TITLE
Firefox is unable to install tldr as a search engine

### ISSUE THREAD

**Issue by tpiekarski** [InBrowserApp/tldr.inbrowser.app#14]
I tried to install https://tldr.inbrowser.app/ as a search engine, using Firefox context menu.
But unfortunately this did not work and failed with following message:

> Invalid Format
> Firefox could not install the search engine from: https://tldr.inbrowser.app/opensearch.xml

I am running Firefox 102.9.0esr on Gentoo GNU/Linux.

Perhaps related to https://github.com/InBrowserApp/tldr.inbrowser.app/issues/12

**Comment by tpiekarski** [comment]
Bump :-)

**Comment by rwv** [comment]
The Firefox error message shows Invalid Format. Maybe this is related to #12, I will try to  open a branch that does not have service worker and try out. 
https://github.com/InBrowserApp/tldr.inbrowser.app/blob/833dd7d6142ceaff298cdb486e34b971df4a6068/public/opensearch.xml
