### ISSUE TITLE
SunOS icon

### ISSUE THREAD

**Issue by yutyo** [InBrowserApp/tldr.inbrowser.app#15]
It would be cool to have the [actual Sun Microsystems icon](https://commons.wikimedia.org/wiki/File:Sun-Logo.svg) there instead of the screen favicon.
![image](https://github.com/InBrowserApp/tldr.inbrowser.app/assets/40173707/bfb678d6-803d-44c9-b64f-409fc871efc1)

**Comment by rwv** [comment]
I am not familiar with the history of sunOS. Can we just use sun microsystem icon?

**Comment by yutyo** [comment]
> I am not familiar with the history of sunOS. Can we just use sun microsystem icon?

I think Sun Microsystem icon is more suitable as machines runnings SunOS had it on them.
